subplot(2,3,1)
plot(A(1,:,1))
title('x');
ylabel('m/s^2');
xlabel('n-Time');
subplot(2,3,2)
plot(A(1,:,2))
title('y');
subplot(2,3,3)
plot(A(1,:,3))
title('z');
subplot(2,3,4)
plot(abs(fft(A(1,:,1))))
ylabel('|FFT|')
xlabel('n-Freq');
subplot(2,3,5)
plot(abs(fft(A(1,:,2))))
subplot(2,3,6)
plot(abs(fft(A(1,:,3))))

